version: '3'

tasks:
    backend:
        cmds:
            - python3 backend_v2.py
    frontend:
        cmds:
            - cd frontend && npm start
    fullstack:
        cmds:
            - task backend &
            - task frontend